/** Central registry of query keys — one place to invalidate from mutations. */
export const queryKeys = {
  status: ['status'] as const,
  agents: ['agents'] as const,
  mail: ['mail'] as const,
  rigs: ['rigs'] as const,
  health: ['health'] as const,
  setup: ['setup'] as const,
  activity: ['activity'] as const,
  convoys: ['convoys'] as const,
  targets: ['targets'] as const,
  beads: (status: string) => ['beads', status] as const,
  beadGraph: ['bead-graph'] as const,
  pullRequests: (state: string) => ['pull-requests', state] as const,
  formulas: ['formulas'] as const,
  schedulerStatus: ['scheduler-status'] as const,
  dogs: ['dogs'] as const,
  escalations: ['escalations'] as const,
  mergeQueue: (rig: string) => ['merge-queue', rig] as const,
  refineryStatus: (rig: string) => ['refinery-status', rig] as const,
  witnessStatus: (rig: string) => ['witness-status', rig] as const,
  doltHealth: ['dolt-health'] as const,
  changelog: (opts: { since?: string; week?: boolean; today?: boolean; rig?: string }) =>
    ['changelog', opts.since ?? '', opts.week ?? false, opts.today ?? false, opts.rig ?? ''] as const,
  rigList: ['rig-list'] as const,
};
